// Keystore service — v4 hardening (H-3).
//
// Wraps the AndroidKeyStore via the "com.passtech.pass_tech/keystore"
// MethodChannel exposed by KeystoreBridge.kt. The KEK lives in the TEE /
// StrongBox and never leaves; only the wrapped (DEK = hwSecret) blob is
// stored in the vault JSON.
//
// `KeystoreBackend` is an interface so unit tests can inject a deterministic
// in-memory fake without booting an emulator. Production code uses
// `ChannelKeystoreBackend`. The migration test uses `InMemoryKeystoreBackend`.
//
// Lifecycle:
//   - setupVault       : createKek(primary) + createKek(decoy) systématique.
//   - encrypt vault    : wrap(alias, hwSecret) → wrappedDek + wrapNonce.
//   - decrypt vault    : unwrap(alias, wrappedDek, wrapNonce) → hwSecret.
//   - deleteVault      : deleteKek(both aliases).
//
// Aliases (decision #4) :
//   - "pt_vault_kek_v1"        : primary slot KEK (always present).
//   - "pt_vault_kek_decoy_v1"  : decoy slot KEK (always present, unused if
//     decoy not configured — preserves plausible deniability).

import 'dart:math';

import 'package:cryptography/cryptography.dart';
import 'package:flutter/services.dart';

/// Canonical KEK alias names. Stored exposed (non-secret) to keep
/// the vault file portable across reinstalls on the same device.
class KeystoreAliases {
  KeystoreAliases._();
  static const primary = 'pt_vault_kek_v1';
  static const decoy = 'pt_vault_kek_decoy_v1';
}

class WrapResult {
  final Uint8List ciphertext;
  final Uint8List nonce;
  const WrapResult({required this.ciphertext, required this.nonce});
}

abstract class KeystoreBackend {
  /// Create a new AES-GCM 256 KEK in the AndroidKeyStore. Idempotent: returns
  /// `false` if the alias already exists.
  Future<bool> createKek(String alias);

  /// Wrap (encrypt) `plaintext` with the KEK referenced by `alias`. The
  /// nonce is generated by the platform.
  Future<WrapResult> wrap(String alias, Uint8List plaintext);

  /// Unwrap (decrypt) `ciphertext` produced by [wrap]. Throws on tag failure.
  Future<Uint8List> unwrap(String alias, Uint8List ciphertext, Uint8List nonce);

  /// True if the KEK exists in the keystore.
  Future<bool> hasKek(String alias);

  /// Delete the KEK. No-op if alias missing.
  Future<void> deleteKek(String alias);
}

/// Production implementation backed by the Kotlin `KeystoreBridge`.
class ChannelKeystoreBackend implements KeystoreBackend {
  static const _channel = MethodChannel('com.passtech.pass_tech/keystore');

  const ChannelKeystoreBackend();

  @override
  Future<bool> createKek(String alias) async {
    final res = await _channel.invokeMethod<bool>(
      'createKek',
      <String, dynamic>{'alias': alias},
    );
    return res ?? false;
  }

  @override
  Future<WrapResult> wrap(String alias, Uint8List plaintext) async {
    final res = await _channel.invokeMethod<Map<Object?, Object?>>(
      'wrap',
      <String, dynamic>{'alias': alias, 'plaintext': plaintext},
    );
    if (res == null) {
      throw StateError('Keystore wrap returned null');
    }
    final ct = res['ciphertext'];
    final nonce = res['nonce'];
    if (ct is! Uint8List || nonce is! Uint8List) {
      throw StateError('Keystore wrap returned malformed payload');
    }
    return WrapResult(ciphertext: ct, nonce: nonce);
  }

  @override
  Future<Uint8List> unwrap(
    String alias,
    Uint8List ciphertext,
    Uint8List nonce,
  ) async {
    final res = await _channel.invokeMethod<Uint8List>(
      'unwrap',
      <String, dynamic>{
        'alias': alias,
        'ciphertext': ciphertext,
        'nonce': nonce,
      },
    );
    if (res == null) {
      throw StateError('Keystore unwrap returned null');
    }
    return res;
  }

  @override
  Future<bool> hasKek(String alias) async {
    final res = await _channel.invokeMethod<bool>('hasKek', <String, dynamic>{
      'alias': alias,
    });
    return res ?? false;
  }

  @override
  Future<void> deleteKek(String alias) async {
    await _channel.invokeMethod<void>('deleteKek', <String, dynamic>{
      'alias': alias,
    });
  }
}

/// In-memory fake for unit tests.
///
/// Uses real AES-GCM-256 via the `cryptography` package, so wrap/unwrap
/// behaves identically to the production bridge (round-trip, tag check,
/// ciphertext||tag layout matching `Cipher.doFinal()` on Android).
///
/// Keys live in a Dart map. NEVER ship to production.
class InMemoryKeystoreBackend implements KeystoreBackend {
  final Map<String, Uint8List> _keks = {};
  static final AesGcm _gcm = AesGcm.with256bits();

  @override
  Future<bool> createKek(String alias) async {
    if (_keks.containsKey(alias)) return false;
    _keks[alias] = _randomBytes(32);
    return true;
  }

  @override
  Future<bool> hasKek(String alias) async => _keks.containsKey(alias);

  @override
  Future<void> deleteKek(String alias) async {
    final k = _keks.remove(alias);
    if (k != null) {
      for (var i = 0; i < k.length; i++) {
        k[i] = 0;
      }
    }
  }

  @override
  Future<WrapResult> wrap(String alias, Uint8List plaintext) async {
    final key = _keks[alias];
    if (key == null) {
      throw StateError('KEK not found for alias');
    }
    final nonce = _randomBytes(12);
    final box = await _gcm.encrypt(
      plaintext,
      secretKey: SecretKey(key),
      nonce: nonce,
    );
    // Mirror Android Cipher.doFinal layout: ciphertext concatenated with tag.
    final ctTag = Uint8List(box.cipherText.length + box.mac.bytes.length);
    ctTag.setRange(0, box.cipherText.length, box.cipherText);
    ctTag.setRange(box.cipherText.length, ctTag.length, box.mac.bytes);
    return WrapResult(ciphertext: ctTag, nonce: Uint8List.fromList(box.nonce));
  }

  @override
  Future<Uint8List> unwrap(
    String alias,
    Uint8List ciphertext,
    Uint8List nonce,
  ) async {
    final key = _keks[alias];
    if (key == null) {
      throw StateError('KEK not found for alias');
    }
    if (ciphertext.length < 16) {
      throw StateError('unwrap: input shorter than GCM tag');
    }
    final ctLen = ciphertext.length - 16;
    final ct = ciphertext.sublist(0, ctLen);
    final tag = ciphertext.sublist(ctLen);
    final box = SecretBox(ct, nonce: nonce, mac: Mac(tag));
    final pt = await _gcm.decrypt(box, secretKey: SecretKey(key));
    return Uint8List.fromList(pt);
  }

  static Uint8List _randomBytes(int n) {
    final rng = Random.secure();
    final out = Uint8List(n);
    for (var i = 0; i < n; i++) {
      out[i] = rng.nextInt(256);
    }
    return out;
  }
}

/// High-level façade used by VaultService. Defaults to the channel backend on
/// Android. Tests inject `InMemoryKeystoreBackend` via the constructor.
class KeystoreService {
  final KeystoreBackend backend;
  const KeystoreService({this.backend = const ChannelKeystoreBackend()});

  /// Decision #4 : create both aliases on every fresh install / setup, so a
  /// keystore inspection cannot reveal whether a decoy slot is in use.
  Future<void> ensureBothKeksExist() async {
    await backend.createKek(KeystoreAliases.primary);
    await backend.createKek(KeystoreAliases.decoy);
  }

  Future<bool> hasKek(String alias) => backend.hasKek(alias);
  Future<bool> createKek(String alias) => backend.createKek(alias);
  Future<void> deleteKek(String alias) => backend.deleteKek(alias);
  Future<WrapResult> wrap(String alias, Uint8List plaintext) =>
      backend.wrap(alias, plaintext);
  Future<Uint8List> unwrap(
    String alias,
    Uint8List ciphertext,
    Uint8List nonce,
  ) => backend.unwrap(alias, ciphertext, nonce);

  Future<void> deleteAll() async {
    await backend.deleteKek(KeystoreAliases.primary);
    await backend.deleteKek(KeystoreAliases.decoy);
  }
}
